import 'package:new_test_for_bloc/widgets/app_bar/custom_app_bar.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_leading_image.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_title.dart';import 'package:flutter/material.dart';import 'package:new_test_for_bloc/core/app_export.dart';class NotificationSettingsScreen extends StatelessWidget {const NotificationSettingsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 29.v), child: Column(children: [_buildRecommendedMusic(context), SizedBox(height: 27.v), _buildNewMusic(context), SizedBox(height: 29.v), _buildPlaylistUpdates(context), SizedBox(height: 26.v), _buildConcertNotifications(context), SizedBox(height: 28.v), _buildArtistUpdates(context), SizedBox(height: 26.v), _buildProductNews(context), SizedBox(height: 26.v), _buildHearMeOffers(context), SizedBox(height: 28.v), _buildNewEpisodes(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 52.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 13.v)), title: AppbarTitle(text: "Notification Settings", margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildRecommendedMusic(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Recommended Music", style: CustomTextStyles.titleMediumSemiBold_1), SizedBox(height: 7.v), Text("Push, Email", style: CustomTextStyles.titleSmallMedium)]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 13.v))]); } 
/// Section Widget
Widget _buildNewMusic(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("New Music", style: CustomTextStyles.titleMediumSemiBold_1), SizedBox(height: 6.v), Text("Push", style: CustomTextStyles.titleSmallMedium)]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 12.v))]); } 
/// Section Widget
Widget _buildPlaylistUpdates(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Playlist Updates", style: CustomTextStyles.titleMediumSemiBold_1), SizedBox(height: 5.v), Text("Push, Email", style: CustomTextStyles.titleSmallMedium)]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 11.v, bottom: 13.v))]); } 
/// Section Widget
Widget _buildConcertNotifications(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Concert Notifications", style: CustomTextStyles.titleMediumSemiBold_1), SizedBox(height: 7.v), Text("Push, Email", style: CustomTextStyles.titleSmallMedium)]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 13.v))]); } 
/// Section Widget
Widget _buildArtistUpdates(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Artist Updates", style: CustomTextStyles.titleMediumSemiBold_1), SizedBox(height: 5.v), Text("Push, Email", style: CustomTextStyles.titleSmallMedium)]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 11.v, bottom: 13.v))]); } 
/// Section Widget
Widget _buildProductNews(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Product News", style: CustomTextStyles.titleMediumSemiBold_1), SizedBox(height: 6.v), Text("Email", style: CustomTextStyles.titleSmallMedium)]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 13.v, bottom: 12.v))]); } 
/// Section Widget
Widget _buildHearMeOffers(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Hearme Offers", style: CustomTextStyles.titleMediumSemiBold_1), SizedBox(height: 7.v), Text("Push, Email", style: CustomTextStyles.titleSmallMedium)]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 13.v))]); } 
/// Section Widget
Widget _buildNewEpisodes(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("New Episodes", style: CustomTextStyles.titleMediumSemiBold_1), SizedBox(height: 5.v), Text("Push, Email", style: CustomTextStyles.titleSmallMedium)]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 11.v, bottom: 13.v))]); } 
 }
