import 'package:new_test_for_bloc/widgets/app_bar/custom_app_bar.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_leading_circleimage.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_subtitle_one.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_subtitle.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_trailing_image.dart';import 'widgets/trendingnowframe_item_widget.dart';import 'widgets/artistsframe_item_widget.dart';import 'widgets/topchartslist_item_widget.dart';import 'package:flutter/material.dart';import 'package:new_test_for_bloc/core/app_export.dart';class HomePage extends StatelessWidget {const HomePage({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 27.v), child: Column(children: [Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildPopularArtistsRow(context, popularArtistsText: "Trending Now", seeAllText: "See All", onTapSeeAllText: () {onTapTxtSeeAllText(context);})), SizedBox(height: 13.v), _buildTrendingNowFrame(context), SizedBox(height: 32.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildPopularArtistsRow(context, popularArtistsText: "Popular Artists", seeAllText: "See All", onTapSeeAllText: () {onTapTxtSeeAllText1(context);})), SizedBox(height: 13.v), _buildArtistsFrame(context), SizedBox(height: 32.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildPopularArtistsRow(context, popularArtistsText: "Top Charts", seeAllText: "See All")), SizedBox(height: 13.v), _buildTopChartsList(context)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 53.v, leadingWidth: 72.h, leading: AppbarLeadingCircleimage(imagePath: ImageConstant.imgEllipse48x48, margin: EdgeInsets.only(left: 24.h, top: 2.v, bottom: 3.v)), title: Padding(padding: EdgeInsets.only(left: 16.h), child: Column(children: [AppbarSubtitleOne(text: "Good Morning 👋", margin: EdgeInsets.only(right: 18.h)), SizedBox(height: 6.v), AppbarSubtitle(text: "Andrew Ainsley")])), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewind, margin: EdgeInsets.only(left: 24.h, top: 12.v, right: 13.h)), AppbarTrailingImage(imagePath: ImageConstant.imgIconsGray90001, margin: EdgeInsets.only(left: 20.h, top: 12.v, right: 37.h))]); } 
/// Section Widget
Widget _buildTrendingNowFrame(BuildContext context) { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 220.v, child: ListView.separated(padding: EdgeInsets.only(left: 24.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: 3, itemBuilder: (context, index) {return TrendingnowframeItemWidget();}))); } 
/// Section Widget
Widget _buildArtistsFrame(BuildContext context) { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 193.v, child: ListView.separated(padding: EdgeInsets.only(left: 24.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: 3, itemBuilder: (context, index) {return ArtistsframeItemWidget();}))); } 
/// Section Widget
Widget _buildTopChartsList(BuildContext context) { return Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(left: 24.h), child: ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 1.v);}, itemCount: 3, itemBuilder: (context, index) {return TopchartslistItemWidget();}))); } 
/// Common widget
Widget _buildPopularArtistsRow(BuildContext context, {required String popularArtistsText, required String seeAllText, Function? onTapSeeAllText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Text(popularArtistsText, style: theme.textTheme.headlineSmall!.copyWith(color: appTheme.gray90001)), GestureDetector(onTap: () {onTapSeeAllText!.call();}, child: Padding(padding: EdgeInsets.only(bottom: 7.v), child: Text(seeAllText, style: CustomTextStyles.titleMediumOnPrimaryContainer16.copyWith(color: theme.colorScheme.onPrimaryContainer))))]); } 
/// Navigates to the trendingNowScreen when the action is triggered.
onTapTxtSeeAllText(BuildContext context) { Navigator.pushNamed(context, AppRoutes.trendingNowScreen); } 
/// Navigates to the popularArtistsScreen when the action is triggered.
onTapTxtSeeAllText1(BuildContext context) { Navigator.pushNamed(context, AppRoutes.popularArtistsScreen); } 
 }
