import 'package:new_test_for_bloc/widgets/app_bar/custom_app_bar.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_leading_image.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_title.dart';import 'package:new_test_for_bloc/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:new_test_for_bloc/core/app_export.dart';class ForgotPasswordScreen extends StatelessWidget {const ForgotPasswordScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 34.v), child: Column(children: [SizedBox(height: 18.v), CustomImageView(imagePath: ImageConstant.imgGroup321, height: 250.v, width: 276.h), SizedBox(height: 34.v), Container(width: 374.h, margin: EdgeInsets.only(right: 5.h), child: Text("Select which contact details should we use to reset your password", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleMediumMedium.copyWith(height: 1.40))), SizedBox(height: 21.v), _buildForgotPasswordRow1(context), SizedBox(height: 24.v), _buildForgotPasswordRow2(context)])), bottomNavigationBar: _buildContinueButton(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 52.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 13.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "Forgot Password", margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildForgotPasswordRow1(BuildContext context) { return Container(padding: EdgeInsets.all(21.h), decoration: AppDecoration.outlineOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder32), child: Row(children: [Container(height: 80.adaptSize, width: 80.adaptSize, padding: EdgeInsets.all(24.h), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder40), child: CustomImageView(imagePath: ImageConstant.imgUser, height: 32.adaptSize, width: 32.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 20.h, top: 16.v, bottom: 16.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("via SMS:", style: CustomTextStyles.titleSmallGray600), SizedBox(height: 10.v), Text("+1 111 ******99", style: CustomTextStyles.titleMedium16)]))])); } 
/// Section Widget
Widget _buildForgotPasswordRow2(BuildContext context) { return Container(padding: EdgeInsets.all(23.h), decoration: AppDecoration.outlineBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder32), child: Row(children: [Container(height: 80.adaptSize, width: 80.adaptSize, padding: EdgeInsets.all(24.h), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder40), child: CustomImageView(imagePath: ImageConstant.imgCheckmarkOnprimarycontainer, height: 32.adaptSize, width: 32.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 20.h, top: 15.v, bottom: 15.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("via Email:", style: CustomTextStyles.titleSmallGray600), SizedBox(height: 11.v), Text("user@domain.com", style: CustomTextStyles.titleMedium16)]))])); } 
/// Section Widget
Widget _buildContinueButton(BuildContext context) { return CustomElevatedButton(text: "Continue", margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 48.v), onPressed: () {onTapContinueButton(context);}); } 

/// Navigates back to the previous screen.
onTapArrowDown(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the filledOtpScreen when the action is triggered.
onTapContinueButton(BuildContext context) { Navigator.pushNamed(context, AppRoutes.filledOtpScreen); } 
 }
