import 'package:new_test_for_bloc/widgets/app_bar/custom_app_bar.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_leading_image.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_title.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_trailing_image.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'package:flutter/material.dart';import 'package:new_test_for_bloc/core/app_export.dart';import 'package:new_test_for_bloc/presentation/new_playlist_bottomsheet/new_playlist_bottomsheet.dart';class PlaylistsScreen extends StatelessWidget {const PlaylistsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 28.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildSortByRow(context), SizedBox(height: 22.v), Divider(), SizedBox(height: 23.v), GestureDetector(onTap: () {onTapTypeListThemeLight(context);}, child: Row(children: [Container(height: 80.adaptSize, width: 80.adaptSize, padding: EdgeInsets.all(24.h), decoration: AppDecoration.gradientRedToOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.circleBorder40), child: CustomImageView(imagePath: ImageConstant.imgCategoriesPlus, height: 32.adaptSize, width: 32.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 16.h, top: 30.v, bottom: 27.v), child: Text("Add New Playlist", style: theme.textTheme.titleMedium))])), SizedBox(height: 24.v), _buildTypeListThemeLightRow(context), SizedBox(height: 24.v), _buildMyFavoritePopRow(context), SizedBox(height: 24.v), _buildLoremIpsumRow(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 53.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 14.v)), title: AppbarTitle(text: "Playlists", margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewind, margin: EdgeInsets.only(left: 24.h, top: 11.v, right: 14.h)), AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgSettingsGray90001, margin: EdgeInsets.only(left: 20.h, top: 11.v, right: 38.h))]); } 
/// Section Widget
Widget _buildSortByRow(BuildContext context) { return Row(children: [Text("Sort by", style: theme.textTheme.titleLarge), Spacer(), Text("Recently Added", style: CustomTextStyles.titleMediumOnPrimaryContainer16), CustomImageView(imagePath: ImageConstant.imgIconlyCurvedSwap, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 12.h, bottom: 4.v))]); } 
/// Section Widget
Widget _buildTypeListThemeLightRow(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 177.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(height: 80.adaptSize, width: 80.adaptSize, padding: EdgeInsets.all(24.h), decoration: AppDecoration.gradientRedToOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.circleBorder40), child: CustomImageView(imagePath: ImageConstant.imgFavoriteWhiteA700, height: 32.adaptSize, width: 32.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.symmetric(vertical: 16.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Your Likes", style: theme.textTheme.titleMedium), SizedBox(height: 9.v), Text("270 songs", style: theme.textTheme.labelLarge)]))])), CustomImageView(imagePath: ImageConstant.imgCategoriesMore, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 30.v))]); } 
/// Section Widget
Widget _buildMyFavoritePopRow(BuildContext context) { return GestureDetector(onTap: () {onTapMyFavoritePopRow(context);}, child: Row(children: [CustomImageView(imagePath: ImageConstant.imgImage84, height: 80.adaptSize, width: 80.adaptSize, radius: BorderRadius.circular(20.h)), Expanded(child: Padding(padding: EdgeInsets.only(left: 16.h, top: 19.v, bottom: 16.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("My Favorite Pop Songs", style: theme.textTheme.titleMedium), SizedBox(height: 6.v), Text("345 songs", style: theme.textTheme.labelLarge)]), CustomImageView(imagePath: ImageConstant.imgCategoriesMore, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 10.v, bottom: 13.v))])))])); } 
/// Section Widget
Widget _buildLoremIpsumRow(BuildContext context) { return GestureDetector(onTap: () {onTapLoremIpsumRow(context);}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 204.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgImage85, height: 80.adaptSize, width: 80.adaptSize, radius: BorderRadius.circular(20.h)), Padding(padding: EdgeInsets.only(top: 19.v, bottom: 16.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("90s Old Song", style: theme.textTheme.titleMedium), SizedBox(height: 7.v), Text("127 songs", style: theme.textTheme.labelLarge)]))])), CustomImageView(imagePath: ImageConstant.imgCategoriesMore, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 30.v))])); } 

/// Shows a modal bottom sheet with [NewPlaylistBottomsheet] 
/// widget content.
/// The sheet is displayed on top of the current view with scrolling enabled if 
/// content exceeds viewport height.
onTapTypeListThemeLight(BuildContext context) { showModalBottomSheet(context: context, builder: (_)=>NewPlaylistBottomsheet(),isScrollControlled: true); } 
/// Navigates to the playlistDetailsScreen when the action is triggered.
onTapMyFavoritePopRow(BuildContext context) { Navigator.pushNamed(context, AppRoutes.playlistDetailsScreen); } 
/// Navigates to the playlistDetailsScreen when the action is triggered.
onTapLoremIpsumRow(BuildContext context) { Navigator.pushNamed(context, AppRoutes.playlistDetailsScreen); } 
 }
