import 'package:new_test_for_bloc/widgets/app_bar/custom_app_bar.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_leading_image.dart';import 'package:flutter/material.dart';import 'package:new_test_for_bloc/core/app_export.dart';class SubscribeScreen extends StatelessWidget {const SubscribeScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 28.v), child: Column(children: [Text("Subscribe to Premium", style: CustomTextStyles.headlineLargeOnPrimaryContainer), SizedBox(height: 13.v), Container(width: 362.h, margin: EdgeInsets.only(left: 9.h, right: 8.h), child: Text("Enjoy listening songs & podcast with better audio quality, without restrictions, and without ads.", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleMediumPrimaryMedium16.copyWith(height: 1.40))), SizedBox(height: 21.v), _buildPremiumSection(context), SizedBox(height: 24.v), _buildPremiumSection2(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIconlyLightOutlineArrow, margin: EdgeInsets.fromLTRB(24.h, 11.v, 376.h, 11.v))); } 
/// Section Widget
Widget _buildPremiumSection(BuildContext context) { return GestureDetector(onTap: () {onTapPremiumSection(context);}, child: Container(padding: EdgeInsets.all(24.h), decoration: AppDecoration.gradientOrangeAToOrangeA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder32), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 7.v), CustomImageView(imagePath: ImageConstant.imgUserWhiteA700, height: 44.v, width: 50.h, alignment: Alignment.center), SizedBox(height: 23.v), Align(alignment: Alignment.center, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("9.99", style: CustomTextStyles.headlineLargeWhiteA700), Padding(padding: EdgeInsets.only(left: 8.h, top: 8.v, bottom: 8.v), child: Text("/month", style: CustomTextStyles.titleMediumGray100))])), SizedBox(height: 15.v), Divider(), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(right: 27.h), child: _buildPremiumSection3(context, text: "Listening with better audio quality")), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(right: 22.h), child: _buildPremiumSection4(context, listeningText: "Listening without restrictions & ads")), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(right: 25.h), child: _buildPremiumSection5(context, shufflePlayText: "Shuffle play & download unlimited"))]))); } 
/// Section Widget
Widget _buildPremiumSection2(BuildContext context) { return Container(padding: EdgeInsets.all(24.h), decoration: AppDecoration.gradientPurpleAToDeepPurpleA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder32), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 7.v), CustomImageView(imagePath: ImageConstant.imgUserWhiteA700, height: 44.v, width: 50.h, alignment: Alignment.center), SizedBox(height: 23.v), Align(alignment: Alignment.center, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("19.99", style: CustomTextStyles.headlineLargeWhiteA700), Padding(padding: EdgeInsets.only(left: 8.h, top: 8.v, bottom: 8.v), child: Text("/3 months", style: CustomTextStyles.titleMediumGray100))])), SizedBox(height: 15.v), Divider(), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(right: 27.h), child: _buildPremiumSection3(context, text: "Listening with better audio quality")), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(right: 22.h), child: _buildPremiumSection4(context, listeningText: "Listening without restrictions & ads")), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(right: 25.h), child: _buildPremiumSection5(context, shufflePlayText: "Shuffle play & download unlimited"))])); } 
/// Common widget
Widget _buildPremiumSection3(BuildContext context, {required String text, }) { return Row(children: [CustomImageView(imagePath: ImageConstant.imgCategoriesCheck, height: 32.adaptSize, width: 32.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 8.v, bottom: 4.v), child: Text(text, style: CustomTextStyles.titleMediumWhiteA700Medium.copyWith(color: appTheme.whiteA700)))]); } 
/// Common widget
Widget _buildPremiumSection4(BuildContext context, {required String listeningText, }) { return Row(children: [CustomImageView(imagePath: ImageConstant.imgCategoriesCheck, height: 32.adaptSize, width: 32.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 8.v, bottom: 4.v), child: Text(listeningText, style: CustomTextStyles.titleMediumWhiteA700Medium.copyWith(color: appTheme.whiteA700)))]); } 
/// Common widget
Widget _buildPremiumSection5(BuildContext context, {required String shufflePlayText, }) { return Row(children: [CustomImageView(imagePath: ImageConstant.imgCategoriesCheck, height: 32.adaptSize, width: 32.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 7.v, bottom: 4.v), child: Text(shufflePlayText, style: CustomTextStyles.titleMediumWhiteA700Medium.copyWith(color: appTheme.whiteA700)))]); } 
/// Navigates to the paymentMethodScreen when the action is triggered.
onTapPremiumSection(BuildContext context) { Navigator.pushNamed(context, AppRoutes.paymentMethodScreen); } 
 }
