import 'package:new_test_for_bloc/widgets/app_bar/custom_app_bar.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_leading_image.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_title.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_trailing_image.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'package:new_test_for_bloc/widgets/custom_elevated_button.dart';import 'package:new_test_for_bloc/widgets/custom_outlined_button.dart';import 'widgets/songs_item_widget.dart';import 'package:flutter/material.dart';import 'package:new_test_for_bloc/core/app_export.dart';class SongsScreen extends StatelessWidget {const SongsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 22.v), child: Column(children: [_buildSortBy(context), SizedBox(height: 22.v), Divider(), SizedBox(height: 23.v), _buildShuffle(context), SizedBox(height: 24.v), _buildSongs(context)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 53.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 14.v)), title: AppbarTitle(text: "Songs", margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewind, margin: EdgeInsets.only(left: 24.h, top: 11.v, right: 14.h)), AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgSettingsGray90001, margin: EdgeInsets.only(left: 20.h, top: 11.v, right: 38.h))]); } 
/// Section Widget
Widget _buildSortBy(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("Sort by", style: theme.textTheme.titleLarge), Spacer(), Text("Recently Downloaded", style: CustomTextStyles.titleMediumOnPrimaryContainer16), CustomImageView(imagePath: ImageConstant.imgIconlyCurvedSwap, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 12.h, bottom: 4.v))]); } 
/// Section Widget
Widget _buildShuffle(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomElevatedButton(text: "Shuffle", margin: EdgeInsets.only(right: 6.h), leftIcon: Container(margin: EdgeInsets.only(right: 16.h), child: CustomImageView(imagePath: ImageConstant.imgCategoriesshuffleComponentadditionalIcons, height: 20.adaptSize, width: 20.adaptSize)))), Expanded(child: CustomOutlinedButton(text: "Play", margin: EdgeInsets.only(left: 6.h), leftIcon: Container(margin: EdgeInsets.only(right: 16.h), child: CustomImageView(imagePath: ImageConstant.imgOverflowmenu, height: 20.adaptSize, width: 20.adaptSize))))]); } 
/// Section Widget
Widget _buildSongs(BuildContext context) { return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: 5, itemBuilder: (context, index) {return SongsItemWidget();}); } 
 }
