import 'package:new_test_for_bloc/widgets/app_bar/custom_app_bar.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_leading_image.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_title.dart';import 'package:new_test_for_bloc/widgets/custom_switch.dart';import 'package:flutter/material.dart';import 'package:new_test_for_bloc/core/app_export.dart';
// ignore_for_file: must_be_immutable
class DataSaverStorageScreen extends StatelessWidget {DataSaverStorageScreen({Key? key}) : super(key: key);

bool isSelectedSwitch = false;

bool isSelectedSwitch1 = false;

bool isSelectedSwitch2 = false;

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 27.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Data Saver", style: theme.textTheme.titleLarge), SizedBox(height: 27.v), _buildAudioQuality(context), SizedBox(height: 21.v), Text("Podcasts", style: theme.textTheme.titleLarge), SizedBox(height: 27.v), _buildDownloadAudioOnly(context), SizedBox(height: 27.v), _buildStreamAudioOnly(context), SizedBox(height: 24.v), Text("Storage", style: theme.textTheme.titleLarge), SizedBox(height: 23.v), _buildCache(context, cacheText: "Other Apps", filesizeText: "75.4 GB"), SizedBox(height: 24.v), _buildCache(context, cacheText: "Cache", filesizeText: "120.6 MB"), SizedBox(height: 27.v), _buildCache(context, cacheText: "Free Space", filesizeText: "50.5 GB"), SizedBox(height: 24.v), _buildRemoveAllDownloads(context), SizedBox(height: 23.v), _buildClearCache(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 52.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 13.v)), title: AppbarTitle(text: "Data Saver & Storage", margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildAudioQuality(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Audio Quality", style: CustomTextStyles.titleMediumSemiBold_1), SizedBox(height: 4.v), SizedBox(width: 251.h, child: Text("Sets your audio quality to low (24kbit/s) and disables artist canvases.", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleSmallMedium.copyWith(height: 1.40)))]), CustomSwitch(margin: EdgeInsets.only(top: 19.v, bottom: 24.v), value: isSelectedSwitch, onChange: (value) {isSelectedSwitch = value;})]); } 
/// Section Widget
Widget _buildDownloadAudioOnly(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Download Audio Only", style: CustomTextStyles.titleMediumSemiBold_1), SizedBox(height: 6.v), Text("Save video podcasts as audio only.", style: CustomTextStyles.titleSmallMedium)]), CustomSwitch(margin: EdgeInsets.only(top: 9.v, bottom: 12.v), value: isSelectedSwitch1, onChange: (value) {isSelectedSwitch1 = value;})]); } 
/// Section Widget
Widget _buildStreamAudioOnly(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Stream Audio Only", style: CustomTextStyles.titleMediumSemiBold_1), SizedBox(height: 4.v), SizedBox(width: 252.h, child: Text("Play video podcasts as audio only when not connected on Wi-Fi.", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleSmallMedium.copyWith(height: 1.40)))]), CustomSwitch(margin: EdgeInsets.only(top: 19.v, bottom: 24.v), value: isSelectedSwitch2, onChange: (value) {isSelectedSwitch2 = value;})]); } 
/// Section Widget
Widget _buildRemoveAllDownloads(BuildContext context) { return Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Remove All Downloads", style: CustomTextStyles.titleMediumSemiBold_1), SizedBox(height: 6.v), SizedBox(width: 278.h, child: Text("Remove all of the Hearme content you have downloaded for offline uses.", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleSmallMedium.copyWith(height: 1.40)))])), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 81.h, top: 23.v, bottom: 26.v))]); } 
/// Section Widget
Widget _buildClearCache(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Clear Cache", style: CustomTextStyles.titleMediumSemiBold_1), SizedBox(height: 6.v), SizedBox(width: 245.h, child: Text("Free up storage without removing your downloaded contents.", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleSmallMedium.copyWith(height: 1.40)))]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 23.v, bottom: 26.v))]); } 
/// Common widget
Widget _buildCache(BuildContext context, {required String cacheText, required String filesizeText, }) { return Row(children: [Text(cacheText, style: CustomTextStyles.titleMediumSemiBold_1.copyWith(color: appTheme.gray90001)), Spacer(), Text(filesizeText, style: CustomTextStyles.titleMediumSemiBold_1.copyWith(color: appTheme.gray90001)), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 20.h))]); } 
 }
