import 'package:new_test_for_bloc/widgets/app_bar/custom_app_bar.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_leading_image.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_title.dart';import 'package:new_test_for_bloc/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'package:new_test_for_bloc/widgets/custom_elevated_button.dart';import 'package:new_test_for_bloc/widgets/custom_switch.dart';import 'package:flutter/material.dart';import 'package:new_test_for_bloc/core/app_export.dart';
// ignore_for_file: must_be_immutable
class ProfileSettingsPage extends StatelessWidget {ProfileSettingsPage({Key? key}) : super(key: key);

bool isSelectedSwitch = false;

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 30.v), child: Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [SizedBox(height: 80.adaptSize, width: 80.adaptSize, child: Stack(alignment: Alignment.bottomRight, children: [CustomImageView(imagePath: ImageConstant.imgEllipse80x80, height: 80.adaptSize, width: 80.adaptSize, radius: BorderRadius.circular(40.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgEdit, height: 20.adaptSize, width: 20.adaptSize, alignment: Alignment.bottomRight)])), Padding(padding: EdgeInsets.only(left: 20.h, top: 15.v, bottom: 15.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Andrew Ainsley", style: theme.textTheme.titleLarge), SizedBox(height: 8.v), Text("user@domain.com", style: theme.textTheme.titleSmall)]))]), SizedBox(height: 23.v), _buildGetPremium(context), SizedBox(height: 24.v), _buildSecurity(context, icon: ImageConstant.imgLock, title: "Profile", onTapSecurity: () {onTapSecurity(context);}), SizedBox(height: 24.v), _buildNotification(context), SizedBox(height: 24.v), _buildAudioVideo(context), SizedBox(height: 24.v), _buildPlayback(context), SizedBox(height: 24.v), _buildDataSaverStorage(context), SizedBox(height: 24.v), _buildSecurity(context, icon: ImageConstant.imgIconlyCurvedShield, title: "Security", onTapSecurity: () {onTapSecurity1(context);}), SizedBox(height: 24.v), _buildLanguage(context), SizedBox(height: 24.v), _buildDarkMode(context), SizedBox(height: 24.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgUserRedA200, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text("Logout", style: CustomTextStyles.titleMediumRedA200))])])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 56.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgVector, margin: EdgeInsets.only(left: 24.h, top: 9.v, bottom: 9.v)), title: AppbarTitle(text: "Profile", margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgSettingsGray90001, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 11.v))]); } 
/// Section Widget
Widget _buildGetPremium(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 23.h), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder32), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 30.v, bottom: 27.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Enjoy All Benefits!", style: CustomTextStyles.headlineSmallWhiteA700), SizedBox(height: 8.v), SizedBox(width: 202.h, child: Text("Enjoy listening songs & podcasts with better audio quality, without restrictions, and without ads.", maxLines: 3, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodySmall)), SizedBox(height: 11.v), CustomElevatedButton(height: 32.v, width: 116.h, text: "Get Premium", buttonStyle: CustomButtonStyles.fillWhiteA, buttonTextStyle: CustomTextStyles.titleSmallOnPrimaryContainer, onPressed: () {onTapGetPremium(context);})])), CustomImageView(imagePath: ImageConstant.imgMusicFococlippingStandard, height: 169.v, width: 115.h, margin: EdgeInsets.only(top: 13.v))])); } 
/// Section Widget
Widget _buildNotification(BuildContext context) { return GestureDetector(onTap: () {onTapNotification(context);}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 144.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgIconsGray90001, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 3.v), child: Text("Notification", style: CustomTextStyles.titleMediumSemiBold_1))])), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 
/// Section Widget
Widget _buildAudioVideo(BuildContext context) { return GestureDetector(onTap: () {onTapAudioVideo(context);}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgMenu, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v, bottom: 3.v), child: Text("Audio & Video", style: CustomTextStyles.titleMediumSemiBold_1))]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 
/// Section Widget
Widget _buildPlayback(BuildContext context) { return GestureDetector(onTap: () {onTapPlayback(context);}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 124.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedPlay, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(top: 5.v), child: Text("Playback", style: CustomTextStyles.titleMediumSemiBold_1))])), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 
/// Section Widget
Widget _buildDataSaverStorage(BuildContext context) { return GestureDetector(onTap: () {onTapDataSaverStorage(context);}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedTick, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text("Data Saver & Storage", style: CustomTextStyles.titleMediumSemiBold_1))]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 
/// Section Widget
Widget _buildLanguage(BuildContext context) { return GestureDetector(onTap: () {onTapLanguage(context);}, child: Row(children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedMore, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text("Language", style: CustomTextStyles.titleMediumSemiBold_1)), Spacer(), Padding(padding: EdgeInsets.only(top: 5.v), child: Text("English (US)", style: CustomTextStyles.titleMediumSemiBold_1)), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 20.h, top: 4.v, bottom: 4.v))])); } 
/// Section Widget
Widget _buildDarkMode(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 139.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgEyeGray90001, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 3.v), child: Text("Dark Mode", style: CustomTextStyles.titleMediumSemiBold_1))])), CustomSwitch(value: isSelectedSwitch, onChange: (value) {isSelectedSwitch = value;})]); } 
/// Common widget
Widget _buildSecurity(BuildContext context, {required String icon, required String title, Function? onTapSecurity, }) { return GestureDetector(onTap: () {onTapSecurity!.call();}, child: Row(children: [CustomImageView(imagePath: icon, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text(title, style: CustomTextStyles.titleMediumSemiBold_1.copyWith(color: appTheme.gray90001))), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 
/// Navigates to the subscribeScreen when the action is triggered.
onTapGetPremium(BuildContext context) { Navigator.pushNamed(context, AppRoutes.subscribeScreen); } 
/// Navigates to the profileDetailsOneScreen when the action is triggered.
onTapSecurity(BuildContext context) { Navigator.pushNamed(context, AppRoutes.profileDetailsOneScreen); } 
/// Navigates to the notificationSettingsScreen when the action is triggered.
onTapNotification(BuildContext context) { Navigator.pushNamed(context, AppRoutes.notificationSettingsScreen); } 
/// Navigates to the audioVideoScreen when the action is triggered.
onTapAudioVideo(BuildContext context) { Navigator.pushNamed(context, AppRoutes.audioVideoScreen); } 
/// Navigates to the playbackScreen when the action is triggered.
onTapPlayback(BuildContext context) { Navigator.pushNamed(context, AppRoutes.playbackScreen); } 
/// Navigates to the dataSaverStorageScreen when the action is triggered.
onTapDataSaverStorage(BuildContext context) { Navigator.pushNamed(context, AppRoutes.dataSaverStorageScreen); } 
/// Navigates to the securityScreen when the action is triggered.
onTapSecurity1(BuildContext context) { Navigator.pushNamed(context, AppRoutes.securityScreen); } 
/// Navigates to the languageScreen when the action is triggered.
onTapLanguage(BuildContext context) { Navigator.pushNamed(context, AppRoutes.languageScreen); } 
 }
